apps/sellers/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from.import views

urlpatterns = [
    path('become-seller/', views.become_seller, name='become_seller'),
    path('seller-admin/', views.seller_admin, name='seller_admin'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_seller/', views.edit_seller, name='edit_seller'),
    path('edit-product/<int:pk>/', views.edit_product, name='edit_product'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('', views.sellers, name='sellers'),
    path('<int:seller_id>', views.seller, name='seller'),
   
]

galaxy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sellers/', include('apps.sellers.urls')),
    path('cart/', include('apps.cart.urls')),
    path('', include('apps.multivendor.urls')),
    path('', include('apps.product.urls')),
    
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/sellers/models.py
from django.contrib.auth.models import User
from django.db import models

class Seller(models.Model):
    name = models.CharField(max_length=225)
    joined_at = models.DateTimeField(auto_now_add=True)
    created_by = models.OneToOneField(User, related_name='seller', on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_balance(self):
        items = self.items.filter(seller_paid=False, order__sellers__in=[self.id])
        return sum((item.product.price * item.quantity) for item in items)
    
    def get_paid_amount(self):
        items = self.items.filter(seller_paid=True, order__sellers__in=[self.id])
        return sum((item.product.price * item.quantity) for item in items)

apps/cart/forms.py
from django import forms

class CheckoutForm(forms.Form):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    phone = forms.CharField(max_length=255)
    address = forms.CharField(max_length=255)
    zipcode = forms.CharField(max_length=255)
    place = forms.CharField(max_length=255)
    stripe_token = forms.CharField(max_length=255)

apps/sellers/forms.py
from django.forms import ModelForm

from apps.product.models import Product, ProductImage

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'image', 'title', 'description', 'price']

class ProductImageForm(ModelForm):
    class Meta:
        model = ProductImage
        fields = ['image']

apps/sellers/views.py
from django.shortcuts import redirect, render ,get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from apps.product.models import Product  
from.models import Seller
from.forms import ProductForm, ProductImageForm

def become_seller(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user =form.save()

            login(request, user)

            seller = Seller.objects.create(name=user.username, created_by=user)
        return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'become_seller.html', {'form': form})

@login_required
def seller_admin(request):
    seller = request.user.seller
    products = seller.products.all()
    orders = seller.orders.all()

    for order in orders:
        order.seller_amount = 0
        order.seller_paid_amount = 0
        order.fully_paid = True

        for item in order.items.all():
            if item.seller == request.user.seller:
                if item.seller_paid:
                    order.seller_paid_amount += item.get_total_price()
                else:
                    order.seller_amount += item.get_total_price()
                    order.fully_paid = False

    return render(request, 'seller_admin.html', {'seller': seller, 'products': products, 'orders': orders})

@login_required
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)

        if form.is_valid():
            product = form.save(commit=False)
            product.seller = request.user.seller
            product.slug = slugify(product.title)
            product.save()

            return redirect('seller_admin')
    else:
        form = ProductForm()
    
    return render(request, 'add_product.html', {'form': form})

@login_required
def edit_product(request, pk):
    seller = request.user.seller
    product = seller.products.get(pk=pk)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        image_form = ProductImageForm(request.POST, request.FILES)

        if image_form.is_valid():
            productimage = image_form.save(commit=False)
            productimage.product = product
            productimage.save()

            return redirect('seller_admin')

        if form.is_valid():
            form.save()

            return redirect('seller_admin')
    else:
        form = ProductForm(instance=product)
        image_form = ProductImageForm()
    
    return render(request, 'edit_product.html', {'form': form, 'image_form': image_form, 'product': product})

@login_required
def edit_seller(request):
    seller = request.user.seller

    if request.method == 'POST':
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')

        if name:
            seller.created_by.email = email
            seller.created_by.save()

            seller.name = name
            seller.save()

            return redirect('seller_admin')
    
    return render(request, 'edit_seller.html', {'seller': seller})


def sellers(request):
    sellers = Seller.objects.all()

    return render(request, 'sellers.html', {'sellers': sellers})

def seller(request, seller_id):
    seller = get_object_or_404(Seller, pk=seller_id)

    return render(request, 'seller.html', {'seller': seller})

apps/sellers/templates/add_product.html
{% extends 'base.html' %}

{% block title %}Adicionar produto {% endblock %}

{% block content %}
<h1>Add Product</h1>
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <div class="field">
        <div class="control">
            <button class="button is-dark is-uppercase">Postar</button>

        </div>
    </div>
</form> 

{% endblock %}

apps/sellers/templates/become_seller.html
{% extends 'base.html' %}

{% block title %}Criar conta{% endblock %}

{% block content %}
<h1><strong>Criar conta MARTK</strong></h1>
</br>
<form method="post" action="." >
    {% csrf_token %}

    {{ form.as_p }}
</br></br>
    <div class="field">
        <div class="control">
            <button class="button is-dark is-uppercase">Se inscrever</button>

        </div>
    </div>
</form> 

<hr>

<h2 class='subtitle'>Já possui conta?</h2>

<a href="{% url 'login' %}">Login</a>
{% endblock %}

apps/sellers/templates/edit_product.html
{% extends 'base.html' %}

{% block title %}Edit product | {% endblock %}

{% block content %}
    <h1 class="title">Editar produto</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <div class="field">
            <div class="control">
                <button class="button is-dark is-uppercase">Salvar mudanças</button>
            </div>
        </div>
    </form>

    <hr>

    <h2 class="subtitle">Imagens</h2>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        {{ image_form.as_p }}

        <div class="field">
            <div class="control">
                <button class="button is-dark is-uppercase">Adicionar imagem</button>
            </div>
        </div>
    </form>
{% endblock %}

apps/sellers/templates/edit_seller.html
{% extends 'base.html' %}

{% block title %}Edit artista | {% endblock %}

{% block content %}
    <h1 class="title">Editar artista</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="field">
            <label>Nome do artista</label>

            <div class="control">
                <input type="text" name="name" id="id_name" value="{{ seller.name }}" class="input">
            </div>

            <p class="help">Não condiz com o usuário!</p>
        </div>

        <div class="field">
            <label>E-mail</label>

            <div class="control">
                <input type="email" name="email" id="id_email" value="{{ seller.created_by.email }}" class="input">
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-dark is-uppercase">Salvar mudanças</button>
            </div>
        </div>
    </form>
{% endblock %}

apps/sellers/templates/login.html
{% extends 'base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<h1>Log in</h1>
<form method="post" action="." >
    {% csrf_token %}

    {{ form.as_p }}

    <div class="field">
        <div class="control">
            <button class="button is-dark is-uppercase">Log in</button>

        </div>
    </div>
</form> 

{% endblock %}

apps/sellers/templates/seller.html
{% extends 'base.html' %}

{% block title %}{{ seller.name }} | {% endblock %}

{% block content %}
    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-text-centered mt-6 mb-6">
            <h2 class="is-size-3">{{ seller.name }}</h2>
        </div>

        {% for product in seller.products.all %}
            {% include 'list_item.html' %}
        {% endfor %}
    </div>
{% endblock %}

apps/sellers/templates/seller_admin.html
{% extends 'base.html' %}

{% block title %}Perfil do Artista{% endblock %}

{% block content %}
<div class="box">
    <h1 class="title">Olá, {{ seller.name }}</h1>

    <strong>Meu saldo: </strong>${{ seller.get_balance }}<br>
    <strong>Total pago: </strong>${{ seller.get_paid_amount }}

        <hr>

        <a href="{% url 'edit_seller' %}" class="button is-info is-upperclass">Editar</a>  
    <a href="{% url 'logout' %}" class="button is-danger is-upperclass">Logout</a>
</div>

<div class="box">
    <h2>Meu Portfólio</h2>
    <a href="{% url 'add_product' %}" class="button is-danger is-upperclass mb-6">Adicionar arte</a>

    {% if products %}
        <table class="table is-fullwidth">
            <thead>
                <th>Título</th>
                <th>Preço</th>
                <th>Ações</th>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td><a href="{% url 'product' product.category.slug product.slug %"}></a>{{ product.title }}</td>
                    <td>{{ product.price }}</td>
                    <td><a href="{% url 'edit_product' product.id %}">Editar</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <p>Você não possui nenhuma arte</p>
    {% endif %}
</div>
<div class="box">
    <h2 class="is-size-3 mb-4">Meus pedidos</h2>

    {% if orders %}
        {% for order in orders %}
            <div class="{% if order.fully_paid %}has-background-success-light{% else %}has-background-info-light{% endif %} mb-2 p-4">
                <div class="columns is-multiline">
                    <div class="column is-6">
                        <h3 class="is-size-4">#{{ order.id }} - {{ order.first_name }} {{ order.last_name }}</h3>
                    </div>

                    <div class="column is-12">
                        <b>Nome:</b> {{ order.first_name }} {{ order.last_name }}<br>
                        <b>Endereço:</b> {{ order.address }}<br>
                        <b>CEP e complemento:</b> {{ order.zipcode }} {{ order.place }}<br>
                        <b>E-mail:</b> {{ order.email }}<br>
                        <b>Telefone:</b> {{ order.phone }}

                        <table class="table is-fullwidth mt-4">
                            <thead>
                                <tr>
                                    <th>Título</th>
                                    <th>Preço</th>
                                    <th>Quantidae</th>
                                    <th>Pago</th>
                                    <th>Total</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for item in order.items.all %}
                                    {% if item.seller == request.user.seller %}
                                        <tr>
                                            <td>{{ item.product.title }}</td>
                                            <td>${{ item.product.price }}</td>
                                            <td>{{ item.quantity }}</td>
                                            <td>{{ item.seller_paid|yesno:"Yes,No" }}</td>
                                            <td>${{ item.get_total_price }}</td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

apps/sellers/templates/sellers.html
{% extends 'base.html' %}

{% block title %}Artistas | {% endblock %}

{% block content %}
    <h1 class="title">Artistas</h1>

    <div class="columns is-multiline">
        {% for seller in sellers %}
            <div class="column is-3">
                <div class="box">
                    <h2 class="subtitle">{{ seller.name }}</h2>

                    <hr>

                    <a href="{% url 'seller' seller.id %}" class="button is-dark is-uppercase">Ver mais</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}